//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetTournoi.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projetTournoi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;connexion&quot; : &quot;sign in&quot;,
        ///	&quot;inscription&quot; : &quot;register&quot;,
        ///	&quot;retour&quot; : &quot;back&quot;,
        ///
        ///	&quot;Cherch_Tour&quot; : &quot;Search a tounament&quot;,
        ///	&quot;Créer_Org&quot; : &quot;Create an organisation&quot;,
        ///	&quot;Créer_Tour&quot; : &quot;Create a tournament&quot;,
        ///
        ///	&quot;Nom&quot; : &quot;Name&quot;,
        ///	&quot;Type&quot; : &quot;Type&quot;,
        ///	&quot;Jeu&quot; : &quot;Game&quot;,
        ///	&quot;Mode&quot; : &quot;Mode&quot;,
        ///	&quot;Ville&quot; : &quot;City&quot;,
        ///	&quot;Rafraîchir&quot; : &quot;Refresh&quot;,
        ///	&quot;Chercher&quot; : &quot;Search&quot;,
        ///
        ///	&quot;Heure&quot; : &quot;Hour&quot;,
        ///	&quot;Pays&quot; : &quot;State&quot;,
        ///	&quot;Rue&quot; : &quot;Street&quot;,
        ///	&quot;Num&quot; : &quot;Num&quot;,
        ///	&quot;Créer&quot; : &quot;Create&quot;,
        ///
        ///	&quot;Description&quot; : &quot;Description&quot;,
        ///
        ///	&quot;Gérer_org&quot; : &quot;Mana [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag_EN {
            get {
                object obj = ResourceManager.GetObject("Flag_EN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag_FR {
            get {
                object obj = ResourceManager.GetObject("Flag_FR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;connexion&quot; : &quot;connexion&quot;,
        ///	&quot;inscription&quot; : &quot;inscription&quot;,
        ///	&quot;retour&quot; : &quot;retour&quot;,
        ///
        ///	&quot;Cherch_Tour&quot; : &quot;Chercher un tournoi&quot;,
        ///	&quot;Créer_Org&quot; : &quot;Créer une organisation&quot;,
        ///	&quot;Créer_Tour&quot; : &quot;Créer un Tournoi&quot;,
        ///
        ///	&quot;Nom&quot; : &quot;Nom&quot;,
        ///	&quot;Type&quot; : &quot;Type&quot;,
        ///	&quot;Jeu&quot; : &quot;Jeu&quot;,
        ///	&quot;Mode&quot; : &quot;Mode&quot;,
        ///	&quot;Ville&quot; : &quot;Ville&quot;,
        ///	&quot;Rafraîchir&quot; : &quot;Rafraîchir&quot;,
        ///	&quot;Chercher&quot; : &quot;Chercher&quot;,
        ///
        ///	&quot;Heure&quot; : &quot;Heure&quot;,
        ///	&quot;Pays&quot; : &quot;Pays&quot;,
        ///	&quot;Rue&quot; : &quot;Rue&quot;,
        ///	&quot;Num&quot; : &quot;Num&quot;,
        ///	&quot;Créer&quot; : &quot;Créer&quot;,
        ///
        ///	&quot;Description&quot; : &quot;Description&quot;,
        ///
        ///	&quot;Gérer_org&quot; :  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
    }
}
