//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetTournoi.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément mail de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailSending", ReplyAction="*")]
        projetTournoi.ServiceReference1.MailSendingResponse MailSending(projetTournoi.ServiceReference1.MailSendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailSending", ReplyAction="*")]
        System.Threading.Tasks.Task<projetTournoi.ServiceReference1.MailSendingResponse> MailSendingAsync(projetTournoi.ServiceReference1.MailSendingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailSendingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailSending", Namespace="http://tempuri.org/", Order=0)]
        public projetTournoi.ServiceReference1.MailSendingRequestBody Body;
        
        public MailSendingRequest() {
        }
        
        public MailSendingRequest(projetTournoi.ServiceReference1.MailSendingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MailSendingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contenu;
        
        public MailSendingRequestBody() {
        }
        
        public MailSendingRequestBody(string mail, string contenu) {
            this.mail = mail;
            this.contenu = contenu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailSendingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailSendingResponse", Namespace="http://tempuri.org/", Order=0)]
        public projetTournoi.ServiceReference1.MailSendingResponseBody Body;
        
        public MailSendingResponse() {
        }
        
        public MailSendingResponse(projetTournoi.ServiceReference1.MailSendingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MailSendingResponseBody {
        
        public MailSendingResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : projetTournoi.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<projetTournoi.ServiceReference1.ServiceSoap>, projetTournoi.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        projetTournoi.ServiceReference1.MailSendingResponse projetTournoi.ServiceReference1.ServiceSoap.MailSending(projetTournoi.ServiceReference1.MailSendingRequest request) {
            return base.Channel.MailSending(request);
        }
        
        public void MailSending(string mail, string contenu) {
            projetTournoi.ServiceReference1.MailSendingRequest inValue = new projetTournoi.ServiceReference1.MailSendingRequest();
            inValue.Body = new projetTournoi.ServiceReference1.MailSendingRequestBody();
            inValue.Body.mail = mail;
            inValue.Body.contenu = contenu;
            projetTournoi.ServiceReference1.MailSendingResponse retVal = ((projetTournoi.ServiceReference1.ServiceSoap)(this)).MailSending(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<projetTournoi.ServiceReference1.MailSendingResponse> projetTournoi.ServiceReference1.ServiceSoap.MailSendingAsync(projetTournoi.ServiceReference1.MailSendingRequest request) {
            return base.Channel.MailSendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<projetTournoi.ServiceReference1.MailSendingResponse> MailSendingAsync(string mail, string contenu) {
            projetTournoi.ServiceReference1.MailSendingRequest inValue = new projetTournoi.ServiceReference1.MailSendingRequest();
            inValue.Body = new projetTournoi.ServiceReference1.MailSendingRequestBody();
            inValue.Body.mail = mail;
            inValue.Body.contenu = contenu;
            return ((projetTournoi.ServiceReference1.ServiceSoap)(this)).MailSendingAsync(inValue);
        }
    }
}
